#!/usr/bin/env python3
"""Generate Go opcode constants from the client packet_enum.h reference."""
from __future__ import annotations

import pathlib
import re
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "internal" / "protocol" / "opcodes_gen.go"
REFERENCE_URL = (
    "https://raw.githubusercontent.com/Topstack-first/20210521_directx_laghaim/"
    "master/start_project/common/packet_enum.h"
)
LOCAL_CANDIDATES = [
    pathlib.Path("/tmp/laghaim-client-ref/packet_enum.h"),
    pathlib.Path("/tmp/laghaim-client/start_project/common/packet_enum.h"),
]

HEADER = """// Code generated by tools/gen_opcodes.py; DO NOT EDIT.

package protocol

// Client-derived opcode counts.
const (
    RequestOpcodeCount = {request_count}
    ResponseOpcodeCount = {response_count}
    UpdateOpcodeCount = {update_count}
)

const (
{request_consts}
)

const (
{response_consts}
)

const (
{update_consts}
)
"""


def load_source() -> str:
    for candidate in LOCAL_CANDIDATES:
        if candidate.exists():
            return candidate.read_text(encoding="latin1")
    with urllib.request.urlopen(REFERENCE_URL, timeout=30) as response:
        return response.read().decode("latin1")


def parse_enum(source: str, enum_name: str) -> list[tuple[str, int]]:
    match = re.search(rf"enum\s+{enum_name}\s*\{{(.*?)\}};", source, re.S)
    if not match:
        raise SystemExit(f"enum {enum_name!r} not found")

    value = -1
    items: list[tuple[str, int]] = []
    for raw_line in match.group(1).splitlines():
        line = raw_line.split("//", 1)[0].strip().rstrip(",")
        if not line or line.endswith("Pack_Max"):
            continue
        if "=" in line:
            name, raw_value = [part.strip() for part in line.split("=", 1)]
            try:
                value = int(raw_value, 0)
            except ValueError as exc:
                raise SystemExit(f"unsupported enum value {raw_value!r} in {enum_name}") from exc
        else:
            name = line
            value += 1
        items.append((name, value))
    return items


def render_block(items: list[tuple[str, int]]) -> str:
    width = max(len(name) for name, _ in items)
    return "\n".join(f"    {name.ljust(width)} Opcode = {value}" for name, value in items)


def main() -> int:
    source = load_source()
    req = parse_enum(source, "RequestPacket")
    res = parse_enum(source, "ResponsePacket")
    upd = parse_enum(source, "UpdatePacket")

    OUT.write_text(
        HEADER.format(
            request_count=len(req),
            response_count=len(res),
            update_count=len(upd),
            request_consts=render_block(req),
            response_consts=render_block(res),
            update_consts=render_block(upd),
        ),
        encoding="utf-8",
    )
    print(f"generated {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
